apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    service: server
spec:
  selector:
    app: server
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: LoadBalancer
