apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  # I am not using Hashicorp Vault due to the time constraints
  user: YWRtaW4=
  password: UmhzRHVDaFZ1Y1RuUUhlRg==
  database: aGVsbG93b3JsZA==
